// ThermiaOnlineAPIConst.js

// General configuration
const THERMIA_CLASSIC_API_CONFIG_URL = "https://online.thermia.se/api/configuration";
const THERMIA_GENESIS_API_CONFIG_URL = "https://online-genesis.thermia.se/api/configuration";

const THERMIA_INSTALLATION_PATH = "/api/v1/Registers/Installations/";

const THERMIA_API_TYPE_CLASSIC = "classic";
const THERMIA_API_TYPE_GENESIS = "genesis";

const THERMIA_API_CONFIG_URLS_BY_API_TYPE = {
    [THERMIA_API_TYPE_CLASSIC]: THERMIA_CLASSIC_API_CONFIG_URL,
    [THERMIA_API_TYPE_GENESIS]: THERMIA_GENESIS_API_CONFIG_URL,
};

// Azure AD configuration
const THERMIA_AZURE_AUTH_URL = "https://thermialogin.b2clogin.com/thermialogin.onmicrosoft.com/b2c_1a_signuporsigninonline";
const THERMIA_AZURE_AUTH_CLIENT_ID_AND_SCOPE = "09ea4903-9e95-45fe-ae1f-e3b7d32fa385";
const THERMIA_AZURE_AUTH_REDIRECT_URI = "https://online-genesis.thermia.se/login";

// Register groups
const REG_GROUP_TEMPERATURES = "REG_GROUP_TEMPERATURES";
const REG_GROUP_OPERATIONAL_STATUS = "REG_GROUP_OPERATIONAL_STATUS";
const REG_GROUP_OPERATIONAL_TIME = "REG_GROUP_OPERATIONAL_TIME";
const REG_GROUP_OPERATIONAL_OPERATION = "REG_GROUP_OPERATIONAL_OPERATION";
const REG_GROUP_HOT_WATER = "REG_GROUP_HOT_WATER";

// Temperature registers
const REG_OUTDOOR_TEMPERATURE = "REG_OUTDOOR_TEMPERATURE"; // Not used
const REG_OPER_DATA_OUTDOOR_TEMP_MA_SA = "REG_OPER_DATA_OUTDOOR_TEMP_MA_SA"; // Not used
const REG_INDOOR_TEMPERATURE = "REG_INDOOR_TEMPERATURE";
const REG_SUPPLY_LINE = "REG_SUPPLY_LINE";
const REG_HOT_WATER_TEMPERATURE = "REG_HOT_WATER_TEMPERATURE";
const REG_BRINE_OUT = "REG_BRINE_OUT";
const REG_BRINE_IN = "REG_BRINE_IN";
const REG_OPER_DATA_BUFFER_TANK = "REG_OPER_DATA_BUFFER_TANK";

// Temperature registers ("classic" specific)
const REG_RETURN_LINE = "REG_RETURN_LINE";
const REG_DESIRED_SUPPLY_LINE = "REG_DESIRED_SUPPLY_LINE";
const REG_OPER_DATA_SUPPLY_MA_SA = "REG_OPER_DATA_SUPPLY_MA_SA";
const REG_DESIRED_SUPPLY_LINE_TEMP = "REG_DESIRED_SUPPLY_LINE_TEMP";
const REG_DESIRED_INDOOR_TEMPERATURE = "REG_DESIRED_INDOOR_TEMPERATURE";

// Temperature registers ("genesis" specific)
const REG_OPER_DATA_RETURN = "REG_OPER_DATA_RETURN";
const REG_DESIRED_SYS_SUPPLY_LINE_TEMP = "REG_DESIRED_SYS_SUPPLY_LINE_TEMP";
const REG_COOL_SENSOR_TANK = "REG_COOL_SENSOR_TANK";
const REG_COOL_SENSOR_SUPPLY = "REG_COOL_SENSOR_SUPPLY";
const REG_ACTUAL_POOL_TEMP = "REG_ACTUAL_POOL_TEMP";

// Operational operation registers
const REG_OPERATIONMODE = "REG_OPERATIONMODE";

// Operational status registers
const REG_OPERATIONAL_STATUS_PRIO1 = "REG_OPERATIONAL_STATUS_PRIO1"; // Operational status for most heat pumps
const COMP_STATUS = "COMP_STATUS"; // Operational status for Diplomat heat pumps
const COMP_STATUS_ITEC = "COMP_STATUS_ITEC"; // Operational status for ITEC heat pumps
const REG_OPERATIONAL_STATUS_PRIORITY_BITMASK = "REG_OPERATIONAL_STATUS_PRIORITY_BITMASK"; // Operational status for Atlas heat pumps
const REG_INTEGRAL_LSD = "REG_INTEGRAL_LSD";
const REG_PID = "REG_PID";

// Hot water registers
const REG_HOT_WATER_STATUS = "REG_HOT_WATER_STATUS";
const REG__HOT_WATER_BOOST = "REG__HOT_WATER_BOOST";

// Operational time registers
const REG_OPER_TIME_IMM1 = "REG_OPER_TIME_IMM1"; // Auxiliary heater 1
const REG_OPER_TIME_IMM2 = "REG_OPER_TIME_IMM2"; // Auxiliary heater 2
const REG_OPER_TIME_IMM3 = "REG_OPER_TIME_IMM3"; // Auxiliary heater 3
const REG_OPER_TIME_COMPRESSOR = "REG_OPER_TIME_COMPRESSOR";
const REG_OPER_TIME_HOT_WATER = "REG_OPER_TIME_HOT_WATER";

// Other
const DATETIME_FORMAT = "%Y-%m-%dT%H:%M:%S";

module.exports = {
    THERMIA_CLASSIC_API_CONFIG_URL,
    THERMIA_GENESIS_API_CONFIG_URL,
    THERMIA_INSTALLATION_PATH,
    THERMIA_API_TYPE_CLASSIC,
    THERMIA_API_TYPE_GENESIS,
    THERMIA_API_CONFIG_URLS_BY_API_TYPE,
    THERMIA_AZURE_AUTH_URL,
    THERMIA_AZURE_AUTH_CLIENT_ID_AND_SCOPE,
    THERMIA_AZURE_AUTH_REDIRECT_URI,
    REG_GROUP_TEMPERATURES,
    REG_GROUP_OPERATIONAL_STATUS,
    REG_GROUP_OPERATIONAL_TIME,
    REG_GROUP_OPERATIONAL_OPERATION,
    REG_GROUP_HOT_WATER,
    REG_OUTDOOR_TEMPERATURE,
    REG_OPER_DATA_OUTDOOR_TEMP_MA_SA,
    REG_INDOOR_TEMPERATURE,
    REG_SUPPLY_LINE,
    REG_HOT_WATER_TEMPERATURE,
    REG_BRINE_OUT,
    REG_BRINE_IN,
    REG_OPER_DATA_BUFFER_TANK,
    REG_RETURN_LINE,
    REG_DESIRED_SUPPLY_LINE,
    REG_OPER_DATA_SUPPLY_MA_SA,
    REG_DESIRED_SUPPLY_LINE_TEMP,
    REG_DESIRED_INDOOR_TEMPERATURE,
    REG_OPER_DATA_RETURN,
    REG_DESIRED_SYS_SUPPLY_LINE_TEMP,
    REG_COOL_SENSOR_TANK,
    REG_COOL_SENSOR_SUPPLY,
    REG_ACTUAL_POOL_TEMP,
    REG_OPERATIONMODE,
    REG_OPERATIONAL_STATUS_PRIO1,
    COMP_STATUS,
    COMP_STATUS_ITEC,
    REG_OPERATIONAL_STATUS_PRIORITY_BITMASK,
    REG_INTEGRAL_LSD,
    REG_PID,
    REG_HOT_WATER_STATUS,
    REG__HOT_WATER_BOOST,
    REG_OPER_TIME_IMM1,
    REG_OPER_TIME_IMM2,
    REG_OPER_TIME_IMM3,
    REG_OPER_TIME_COMPRESSOR,
    REG_OPER_TIME_HOT_WATER,
    DATETIME_FORMAT
};
